# Login - Valid Data
login.valid.username=Login
login.valid.password=Password

# Login - placeholder
login.placeholder.username=\u041B\u043E\u0433\u0438\u043D
login.placeholder.password=\u041F\u0430\u0440\u043E\u043B\u044C

# Expected Results
expected.error.message=InvalidValue