# Login - Valid Data
login.valid.username=Login
login.valid.password=Password

# Login - placeholder
login.placeholder.username=Логин
login.placeholder.password=Пароль

# Expected Results
expected.error.message=InvalidValue